### ISSUE TITLE
Anatomist object id in createGraph not found

### ISSUE THREAD

**Issue by Hboni** [brainvisa/anatomist-free#19] opened 2020-08-04 08:20 UTC
On a casa_distro with ubuntu 18 in python3, the createGraph method of Anatomist doesn't work.
I tried to use it in python and it gives the same output. It returns :
```
In [8]: region = a.createGraph(object=aimage, name=image_path, filename=image_path)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-fb2a936cb766> in <module>
----> 1 region = a.createGraph(object=aimage, name=image_path, filename=image_path)

/casa/build/python/anatomist/direct/api.py in createGraph(self, object, name, syntax, filename)
    459         self.execute("CreateGraph", object=object, res_pointer=newGraphId,
    460                      name=name, syntax=syntax, filename=filename)
--> 461         newGraph = self.AGraph(self, self.context.object(newGraphId))
    462         newGraph.releaseAppRef()
    463         return newGraph

RuntimeError: ID not found
```
It seems that the `CreateGraph` anatomist command doesn't work, but I don't know how to test it in the Anatomist command processor

**Comment by denisri** [comment] 2020-08-04 08:43
I have tried it (outside of casa-distro but it should not make any difference) and it worked for me. Maybe you did not use it the way it was intended ? This function creates a graph (ROI or other) based on the dimensions of another object (typically a volume), so you have to give it a valid anatomist object with appropriate dimensions and voxel size. For instance:
```import anatomist.api as ana
a = ana.Anatomist()
vol = a.loadObject('image.nii')
graph = a.createGraph(object=vol, name='some_name', filename='/tmp/my_graph.arg')
```
Have you done the same ?

**Comment by Hboni** [comment] 2020-08-04 13:57
I just forget to mention that it works in python2 and not in my python3 version.

The only major difference with your code sample is the `'-b'` in the Anatomist call. I tried : 
```
a = ana.Anatomist('-b')
aimage = a.loadObject('image.nii')
region = a.createGraph(object=aimage, name='/tmp/test.arg', filename='/tmp/test.arg')
```

If I try `aimage.getInfo()`, it looks like the object is loaded correctly.

**Comment by denisri** [comment] 2020-08-05 08:17
Weird, it works for me in python3 also...

**Comment by denisri** [comment] 2021-10-04 16:51
No news from this for more than a year, and I still can't reproduce it, so I close it, and if it happens again, please reopen it.

**Closed as completed by denisri** 2021-10-04 16:51 UTC
